### ISSUE TITLE
Experience displayed on NPC

### ISSUE THREAD

**Issue by SlimeDog** [PaulAnthonyReitz/ReitzMMO#10]
**EDIT: issue updated to current versions**
Spigot 1.15.1
ReitzMMO 1.20

ChatSettings/ChatConfig.yml
```
# This config is used to configure chat output from the plugin
expHologramsEnabled: false
expChatEnabled: false
```
NPC displays +EXP heart. "Jack" is a PLAYER type NPC, created by Citizens.

![2019-05-27_02 27 49](https://user-images.githubusercontent.com/17748923/58410819-d361e980-8027-11e9-9451-bbab39cef116.png)

**Comment by SlimeDog** [comment]
I guess it was a bug. No hurry. We uninstalled ReitzMMO eight months ago, due to this issue.

**Comment by RitzDaCat** [comment]
Checking if an entity is a Citizens NPC
Citizens NPCs will have the "NPC" metadata set to true. Eg.
boolean isCitizensNPC = entity.hasMetadata("NPC");

   @EventHandler(priority= EventPriority.HIGHEST)
    public void scoreboard(PlayerJoinEvent e) {

        if(!(e.getPlayer().hasMetadata("NPC")))
        {
            try
            {
                Scoreboard sb = Objects.requireNonNull(Bukkit.getScoreboardManager()).getMainScoreboard();

                Objective objective = sb.registerNewObjective("showhealth", "health");
                objective.setDisplaySlot(DisplaySlot.BELOW_NAME);
                objective.setDisplayName(ChatColor.RED + "❤");

                for (Player online : Bukkit.getOnlinePlayers()) {

                    if(!(online.hasMetadata("NPC"))) {
                        online.setScoreboard(sb);
                        online.setHealth(online.getHealth());
                    }
                }
            }
            catch (IllegalArgumentException ignored)
            {

            }
    }
    }
}

**Comment by SlimeDog** [comment]
So this is a feature? Could it be made configurable?

**Comment by RitzDaCat** [comment]
@SlimeDog , it could be configurable if you want Citizen NPC's to display. I have this labelled as a bug as it is unintended but if you would like it to be a configurable value then I can do a enhancement request and change this around.

**Comment by SlimeDog** [comment]
I didn't want it to be configurable. That was just a suggestion, since you closed the bug. I would have preferred it to go away altogether. But as I noted above, we don't use the plugin anymore, so we attach no urgency to a resolution.

**Comment by SlimeDog** [comment]
If I'm reading correctly, this was fixed in the latest update. Thanks. When we get some bandwidth, we'll give it a retry.

**Comment by SlimeDog** [comment]
This issue still exists in ReitzMMO 1.20. Am I missing a configuration option, or did I misunderstand that it was fixed?

**Comment by SlimeDog** [comment]
It looks like MonsterSettings/MonsterConfig.yml
```
General:
  nameplates-enabled: false
```
does what I wanted. No names and no experience hologram. Is this the expected result?

**Comment by RitzDaCat** [comment]
Nameplates disabled was designed to hide the names of creatures so if that
is what you desired then that would make sense. As for the hologram exp
that is another setting.

**Comment by SlimeDog** [comment]
(Note that I removed the erroneous comment to which you responded. The holograms still display, despite plugins/ReitzMMO/ChatSettings/ChatConfig.yml
```
expHologramsEnabled: false
expChatEnabled: false
```

**Comment by RitzDaCat** [comment]
Let's make a bug report for the holograms displaying and I'll take a look
at it.

**Comment by SlimeDog** [comment]
Please review the first comment, now updated to reflect current versions, in which the issue still exists.
