### ISSUE TITLE
I can see the monster names through the walls

### ISSUE THREAD

**Issue by avalon666** [PaulAnthonyReitz/ReitzMMO#13]
I can see the monster names through the walls. A change of _nameplates-enabled: false/true_ does not bring any change.

**Comment by avalon666** [comment]
After a reset of the plugin the problem seems to be gone. I'll watch it.

**Comment by RitzDaCat** [comment]
The nameplates occur on monster spawn but if you toggle the setting it won't change a previously spawned mob. I can modify and create a check for this.

**Comment by avalon666** [comment]
Okay, thanks for the information.
