### ISSUE TITLE
Error fighting with mob

### ISSUE THREAD

**Issue by avalon666** [PaulAnthonyReitz/ReitzMMO#14]
[Error](https://pastebin.com/Uj6kbYnw)

**Comment by avalon666** [comment]
After updating Worldguard to 7.0.0-SNAPSHOT-dist#1903-426a709 the error was gone. Since the update of ReitzMMO to 1.16 the [bug](https://pastebin.com/dtdQw60v) is back.

**Comment by RitzDaCat** [comment]
Believe this was caused by a JavaIllegalException where a mob did not have a name assigned or it had issues parsing the value. Believe I have this fixed in the next update.

**Comment by avalon666** [comment]
Sorry, it's me again. ;-D
[Mob-Error](https://pastebin.com/B54hr3QA)

**Comment by RitzDaCat** [comment]
This should be resolved in 1.20 with the new system as I got away from checking mob names.
