### ISSUE TITLE
All salmon will be killed

### ISSUE THREAD

**Issue by avalon666** [PaulAnthonyReitz/ReitzMMO#15]
All salmon will be killed. But many Squid appear. Raw fish or bean meal from the killed salmon floats in the water.

**Comment by avalon666** [comment]
Without plugin the spawn behaviour of Salmon and Squid is normal. With plugin despawn the salmon immediately when you are near.

**Comment by RitzDaCat** [comment]
f9de73ecc6d1e94fc455b9ae667ee3edc3dffd7e

Had this included in this push, will be fixed in 1.17. Salmon were sometimes spawning with 0 hp and dying. Thanks for reporting!
