### ISSUE TITLE
Permissions, please

### ISSUE THREAD

**Issue by SlimeDog** [PaulAnthonyReitz/ReitzMMO#5]
Spigot 1.14.1
ReitzMMO 1.14

There do not appear to be permissions nodes. Please implement a minimal set, like
**reitzmmo.use** to use commands
**reitzmmo.gui** to use GUI
**reitzmmo.reload** to reload the configurations

**Comment by RitzDaCat** [comment]
https://github.com/PaulAnthonyReitz/ReitzMMO/commit/63c9caeb5aee29240b6f5991cec97851755c45fe
