### ISSUE TITLE
Player data storage

### ISSUE THREAD

**Issue by SlimeDog** [PaulAnthonyReitz/ReitzMMO#6]
Spigot 1.14.1
ReitzMMO 1.14

Player data should be stored by UUID, not playerName. The current configuration allows a player to change their name, which they do often, with the loss of player data when they connect with the new playerName. The last known playerName could be stored for convenience, but the UUID should rule.

Unless it is a different concept, player health should be obtained from the system, not stored locally.

**Comment by RitzDaCat** [comment]
6ef43847a604502c6288be8c19ce2b1aeaba8e0f

**Comment by SlimeDog** [comment]
Confirmed fixed in v 1.15. Thanks.
